version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lbs-postgres
    environment:
      POSTGRES_DB: lbs_db
      POSTGRES_USER: lbs_user
      POSTGRES_PASSWORD: lbs_password
    ports:
      - "5433:5432"
  #  ton PC (localhost:5433)  →→→  conteneur Docker (5432)
  #  Pourquoi localhost au niveau de host ?
  #
  #  Dans pgAdmin (qui est dans un conteneur) → on utilise lbs-postgres
  #  Dans DBeaver/DataGrip (qui est sur ton PC) → on utilise localhost

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lbs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lbs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"

  maildev:
    image: maildev/maildev:latest
    container_name: lbs-maildev
    ports:
      - "1081:1080"

  keycloak-postgres:
    image: postgres:latest
    container_name: lbs-keycloak-postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5434:5432"
  #  Base de données dédiée à Keycloak (séparée de lbs_db)
  #  Dans Keycloak → on utilise keycloak-postgres (nom du conteneur)
  #  Dans DBeaver/DataGrip (sur ton PC) → on utilise localhost:5434

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: lbs-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-postgres
#  Admin Console → http://localhost:8080
#  Dans ton app Spring Boot → http://keycloak:8080 (nom du conteneur)

  minio:
    image: minio/minio:latest
    container_name: lbs-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: