-- Création du schéma lbs si inexistant
CREATE SCHEMA IF NOT EXISTS lbs;

-- Donner tous les droits à l'utilisateur lbs_user
GRANT ALL PRIVILEGES ON SCHEMA lbs TO lbs_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA lbs TO lbs_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA lbs TO lbs_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA lbs GRANT ALL ON TABLES TO lbs_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA lbs GRANT ALL ON SEQUENCES TO lbs_user;
