spring.application.name=lbs-backend

# Base de données
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/lbs_db?currentSchema=lbs
spring.datasource.username=${DB_USERNAME:lbs_user}
spring.datasource.password=${DB_PASSWORD:lbs_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=lbs

# ============================================
# Mail - Gmail SMTP
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=loickzannou4@gmail.com
spring.mail.password=sltjhuglntmoqucsr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.from=LBS Education <loickzannou4@gmail.com>

# ============================================
# Keycloak - OAuth2 Resource Server (JWT)
# ============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lbs-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/lbs-realm/protocol/openid-connect/certs

# ============================================
# Keycloak - Admin Client Setup
# ============================================
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.admin.target-realm=lbs-realm

# Logging (INFO en dev, ajuster en production)
logging.level.org.springframework.security=INFO

# ============================================
# le port sur lequel va demarrer mon backend
# ============================================
server.port=8082

# ============================================
# MinIO - Stockage de fichiers
# ============================================
minio.url=http://localhost:9000
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=lbs-files

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
