spring.application.name=lbs-backend

# Base de donnÃ©es
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/lbs_db?currentSchema=lbs
spring.datasource.username=lbs_user
spring.datasource.password=lbs_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=lbs

# Maildev
spring.mail.host=localhost
spring.mail.port=1026

# ============================================
# Keycloak - OAuth2 Resource Server (JWT)
# ============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/lbs-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/lbs-realm/protocol/openid-connect/certs

# ============================================
# Keycloak - Admin Client Setup
# ============================================
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.target-realm=lbs-realm

# Logging (pour debug auth)
logging.level.org.springframework.security=DEBUG
# ============================================
# le port sur lequel va demarrer mon backend
# ============================================
server.port=8082

# ============================================
# MinIO - Stockage de fichiers
# ============================================
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=lbs-files

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
